dist: xenial
sudo: required
language: cpp
os: linux

matrix:
  include:

  #####
  ## Clang on macOS
  #####

  # xcode 9.4
  - os: osx
    osx_image: xcode9.4

  # xcode 10.2
  - os: osx
    osx_image: xcode10.2

  #####
  ## Clang on Linux
  #####

  # clang 6
  - addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-xenial-6
        packages:
          - clang-6.0
          - uuid-dev
    env:
      - SET_COMPILERS="CC=clang-6.0 && CXX=clang++-6.0"

  # clang 7
  - addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-xenial-7
        packages:
          - clang-7
          - uuid-dev
    env:
      - SET_COMPILERS="CC=clang-7 && CXX=clang++-7"

  # clang 8
  - addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-xenial-8
        packages:
          - clang-8
          - uuid-dev
    env:
      - SET_COMPILERS="CC=clang-8 && CXX=clang++-8"

  #####
  ## GCC on Linux
  #####

  # gcc 7
  - addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - uuid-dev
    env:
      - SET_COMPILERS="CC=gcc-7 && CXX=g++-7"

  # gcc 8
  - addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
          - uuid-dev
    env:
      - SET_COMPILERS="CC=gcc-8 && CXX=g++-8"

  # gcc 9
  - addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-9
          - uuid-dev
    env:
      - SET_COMPILERS="CC=gcc-9 && CXX=g++-9"

before_install:
  # We have to do this here instead of just setting the env vars in the matrix
  # because the compilers need to override the default setup
  - eval "${SET_COMPILERS}"

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE="Debug"

script:
  - cmake --build . -- -j${JOBS} && sudo make install
  - ./crossguid-test
